M48
; DRILL file {KiCad (6.0.11)} date Sun Apr 14 00:11:41 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-14T00:11:41+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X53.0Y-57.1
X53.0Y-157.1
X153.0Y-57.1
X153.0Y-157.1
T0
M30
